CabinetBundle\Entity\Contact:
    type: entity
    table: contact
#primary key
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
        prenom:
            type: string
        specialite:
            type: string
        adresse:
            type: string
        numTel:
            type: string