CabinetBundle\Entity\Secretaire:
    type: entity
    table: secretaire
#primary key
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        cin:
            type: string
        numContrat:
            type: string
        dateDebContrat:
            type: date
        dateFinContrat:
            type: date
        nom:
            type: string
            length: 30
        prenom:
            type: string
            length: 30
        dateNaissance:
            type: date
        adresse:
            type: string
            length: 150
            nullable: true
        numTel:
            type: string
            length: 20
        genre:
            type: string
            length: 10
    oneToMany:
        rdvs:
            targetEntity: Rdv
#mapped by designe le nom de la relation dans l'autre classe de la realtion(au lieu de secretaire : creePar)
            mappedBy: creePar
        patients:
            targetEntity: Patient
            mappedBy: creePar
    oneToOne:
        user:
            targetEntity: UserBundle\Entity\User
            inversedBy: secretaire
            cascade: [persist]