CabinetBundle\Entity\SecuriteSocial:
    type: entity
    table: securite_social
#primary key
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        type:
            type: string
        dateExpiration:
            type: date
    manyToMany:
        patients:
            targetEntity: Patient
            mappedBy: securiteSocials